server:
  port: 8080
spring:
  application:
    name: "clean-architecture"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  restconsumer:
    public-key: "8b9c115eb9bde733f129c086b181e69a"
    private-key: "27ecabfbd457994f2dbca14cc86362d9975b5566"
    ts: "1"
    timeout: 5000
    url: "https://gateway.marvel.com/v1/public/characters"
